### ISSUE TITLE
cospectrum failing with memory error after shift from types in columns instead of rows

### ISSUE THREAD

**Issue by hsosik** [hsosik/NES-LTER#4]
It seems like something might be wrong with how cospectrum is called from  tsvr_all_sigma.m after the change from types as columns instead of rows? It will run with short time series, but fails as below for time series with many points (such as MVCO). 

Error in MATLAB:

Error using zeros
Requested 7201x7201x7201 (2782.1GB) array exceeds maximum array size preference (15.7GB). This might
cause MATLAB to become unresponsive.

Error in cospectrum (line 12)
cosp=zeros(npops,npops,tslength);

Error in tsvr_all_sigma (line 21)
    [h_cosp,h_freq]=cospectrum(ts_pops(:,k));

**Comment by svdaalen** [comment]
I double-checked the files in my local sandbox and they are working, but now I'm having some issues pushing them to the repo. I suspect I tweaked something yesterday before I pushed, but forgot a transpose somewhere. I'm working on resolving my push problems, in the meantime, I'll send you the working files, feel free to push them from your computer!

**Comment by hsosik** [comment]
updated m-files from Silke pushed in commit [a24a4f2](https://github.com/hsosik/NES-LTER/commit/a24a4f2e60aa1598f7a839ced18a3f9f63c1783c)
